DROP SCHEMA IF EXISTS 'ims';

CREATE SCHEMA `ims`;

USE `ims` ;

CREATE TABLE IF NOT EXISTS customers (
    id INT(11) NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(40) DEFAULT NULL,
    surname VARCHAR(40) DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS orders (
    id INT(11) NOT NULL AUTO_INCREMENT,
    cust_id VARCHAR(40) DEFAULT NULL,
    date DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (cust_id) REFERENCES customers(id)
);

CREATE TABLE IF NOT EXISTS order_items (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `cust_id` VARCHAR(40) DEFAULT NULL,
    `date` DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    FOREIGN KEY ('cust_id')
);

CREATE TABLE IF NOT EXISTS items (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `item_name` VARCHAR(40) DEFAULT NULL,
    `date` DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    FOREIGN KEY ('cust_id')
);